name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://exthm-my.sharepoint.com/personal/cd1a_exthmui_cn/_layouts/15/download.aspx?UniqueId=a6997413-2139-499e-b4fa-8205113651db&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvZXh0aG0tbXkuc2hhcmVwb2ludC5jb21ANjQ1ZTA2YWEtOTg3Zi00OWEyLTg0MjQtMWMzN2JhN2I3NDAwIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU5NjQ0MjUyNCIsImV4cCI6IjE1OTY0NDYxMjQiLCJlbmRwb2ludHVybCI6IlNkb2U2YXMwdWR0R0IwTHVXL0xNMGN3MUVMcmxrQzVoYTVSa3AweUp5YzA9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNDQiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6IlkyWmhNVGxoTkRjdFkyWTFOUzAwTUdZM0xUbGxPR0V0T0RnNE56RmlZVEV6TkRBNCIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJNVEl4TURnNFlXWXRORFJqT1MwME5XVXlMVGhtTXprdFlUVTNOek5sTlRrd09XSm0iLCJhcHBfZGlzcGxheW5hbWUiOiJQeW9uZTIiLCJhcHBpZCI6IjAwZjAwMTRjLTkwYWEtNDE3YS1iMWVhLWZiN2QxNGY1ODdkOSIsInRpZCI6IjY0NWUwNmFhLTk4N2YtNDlhMi04NDI0LTFjMzdiYTdiNzQwMCIsInVwbiI6ImNkMWFAZXh0aG11aS5jbiIsInB1aWQiOiIxMDAzMjAwMEMwRjQ4MTkzIiwiY2FjaGVrZXkiOiIwaC5mfG1lbWJlcnNoaXB8MTAwMzIwMDBjMGY0ODE5M0BsaXZlLmNvbSIsInNjcCI6Im15ZmlsZXMud3JpdGUgYWxsZmlsZXMud3JpdGUiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.ZzcxRm1sd21VK2YwUWoreTFEdU5QaXMxV1doZktVVFVDUVROd2RVT0JKMD0&ApiVersion=2.0
  ROM_NAME: Generic
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/wwrrj/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME --ab
       
       - name: Zip GSI  
         run: |
              mkdir final
              zip -r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
       
       - name: Upload GSI to transfer
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet final/GSI.zip

         
            
